id: PF7E05CB5
initial_creation_type: ocr
source_metadata:
  volumes:
    66101a5d195f443badf0851b00923596:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: བསྟན་བཅོས་བཞི་བརྒྱ་པ་ཞེས་བྱ་བའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
